# ---
# - name: Automated Deployment and Configuration with Ansible for NESTJS
#   hosts: hng
#   become: yes
#   vars:
#     repo_url: 'https://github.com/hngprojects/hng_boilerplate_nestjs.git'
#     branch: 'devops'
#     app_dir: '/opt/stage_5b'
#     pg_password: 'babatunde_25'  # Replace with a secure password or generate dynamically
#     db_name: 'ansible_deployment'
#     db_user: 'alaomichael'
#     db_host: 'localhost'
#     db_port: 5432
#     ansible_remote_tmp: "/tmp/ansible_tmp"  # Define a tmp directory with permissions

#   tasks:
#     - name: Ensure /tmp/ansible_tmp directory has correct permissions
#       file:
#         path: "{{ ansible_remote_tmp }}"
#         state: directory
#         mode: '1777'
#         owner: root
#         group: root

#     - name: Ensure /tmp has correct permissions
#       file:
#         path: /tmp
#         state: directory
#         mode: '1777'

#     - name: Create a user-specific temporary directory
#       file:
#         path: "{{ ansible_remote_tmp }}/{{ ansible_user_id }}"
#         state: directory
#         mode: '0700'

#     - name: Update apt package index
#       apt:
#         update_cache: yes

#     - name: Install required packages
#       apt:
#         name:
#           - git
#           - python3-pip
#           - nginx
#           - postgresql
#           - postgresql-contrib
#           - rabbitmq-server
#           - npm
#           - curl
#           - wget
#           - gnupg
#           - lsb-release
#         state: present

#     - name: Create application directory
#       file:
#         path: "{{ app_dir }}"
#         state: directory
#         mode: '0755'

#     - name: Clone the devops branch of the repository
#       git:
#         repo: "{{ repo_url }}"
#         dest: "{{ app_dir }}"
#         version: "{{ branch }}"
#         force: yes

#     - name: Install nvm (Node Version Manager)
#       shell: |
#         curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
#         export NVM_DIR="$HOME/.nvm"
#         [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
#         [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
#       environment:
#         HOME: "{{ ansible_env.HOME }}"
#       args:
#         executable: /bin/bash

#     - name: Install Node.js and npm using nvm
#       shell: |
#         export NVM_DIR="$HOME/.nvm"
#         [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
#         nvm install 18
#         nvm use 18
#       environment:
#         HOME: "{{ ansible_env.HOME }}"
#       args:
#         executable: /bin/bash

#     - name: Install Node.js dependencies
#       shell: |
#         export NVM_DIR="$HOME/.nvm"
#         [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
#         npm install
#       environment:
#         HOME: "{{ ansible_env.HOME }}"
#       args:
#         chdir: "{{ app_dir }}"
#         executable: /bin/bash

#     - name: Add hng user with sudo privileges
#       user:
#         name: hng
#         shell: /bin/bash
#         groups: sudo
#         append: yes

#     - name: Clone the devops branch of the repository
#       git:
#         repo: "{{ repo_url }}"
#         dest: "{{ app_dir }}"
#         version: "{{ branch }}"
#         force: yes

#     - name: Ensure /var/secrets directory exists
#       file:
#         path: /var/secrets
#         state: directory
#         mode: '0755'

#     - name: Save PostgreSQL admin credentials
#       copy:
#         dest: /var/secrets/pg_pw.txt
#         content: "{{ db_user }}:{{ pg_password }}"
#         mode: '0600'

#     - name: Ensure /var/log/stage_5b directory exists
#       file:
#         path: /var/log/stage_5b
#         state: directory
#         mode: '0755'

#     - name: Configure PostgreSQL database
#       postgresql_db:
#         name: "{{ db_name }}"
#         state: present

#     - name: Create PostgreSQL user
#       postgresql_user:
#         name: "{{ db_user }}"
#         password: "{{ pg_password }}"
#         priv: "ALL"
#         state: present

#     - name: Configure RabbitMQ
#       rabbitmq_user:
#         user: guest
#         password: guest
#         vhost: /
#         configure_priv: .*
#         read_priv: .*
#         write_priv: .*
#         state: present

#     - name: Configure environment variables
#       copy:
#         dest: "{{ app_dir }}/.env"
#         content: |
#           DATABASE_URL=postgres://{{ db_user }}:{{ pg_password }}@{{ db_host }}:{{ db_port }}/{{ db_name }}
#           RABBITMQ_URL=amqp://guest:guest@localhost:5672/
#           PORT=3000
#         mode: '0644'

#     - name: Start the application
#       command: "nohup npm run start:prod > /var/log/stage_5b/out.log 2> /var/log/stage_5b/error.log &"
#       args:
#         chdir: "{{ app_dir }}"

#     - name: Set ownership of log files
#       file:
#         path: "/var/log/stage_5b"
#         state: directory
#         recurse: yes
#         owner: hng
#         group: hng

#     - name: Configure Nginx to reverse proxy
#       copy:
#         dest: /etc/nginx/sites-available/stage_5b
#         content: |
#           server {
#               listen 80;

#               server_name _;

#               location / {
#                   proxy_pass http://127.0.0.1:3000;
#                   proxy_set_header Host $host;
#                   proxy_set_header X-Real-IP $remote_addr;
#                   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#                   proxy_set_header X-Forwarded-Proto $scheme;
#               }
#           }
#       notify: Restart nginx

#     - name: Enable Nginx site
#       file:
#         src: /etc/nginx/sites-available/stage_5b
#         dest: /etc/nginx/sites-enabled/stage_5b
#         state: link

#     - name: Remove default Nginx site
#       file:
#         path: /etc/nginx/sites-enabled/default
#         state: absent

#   handlers:
#     - name: Restart nginx
#       service:
#         name: nginx
#         state: restarted


---
- name: Automated Deployment and Configuration with Ansible for NESTJS
  hosts: hng
  become: yes
  vars:
    repo_url: 'https://github.com/hngprojects/hng_boilerplate_nestjs.git'
    branch: 'devops'
    app_dir: '/opt/stage_5b'
    pg_password: 'babatunde_25'
    db_name: 'ansible_deployment'
    db_user: 'alaomichael'
    db_host: 'localhost'
    db_port: 5432
    ansible_remote_tmp: "/tmp/ansible_tmp"

  tasks:
    - name: Ensure /tmp/ansible_tmp directory has correct permissions
      file:
        path: "{{ ansible_remote_tmp }}"
        state: directory
        mode: '1777'
        owner: root
        group: root

    - name: Ensure /tmp has correct permissions
      file:
        path: /tmp
        state: directory
        mode: '1777'

    - name: Create application directory
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0755'

    - name: Ensure /var/log/stage_5b directory exists
      file:
        path: /var/log/stage_5b
        state: directory
        mode: '0755'

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - git
          - python3-pip
          - nginx
          - postgresql
          - postgresql-contrib
          - rabbitmq-server
          - npm
          - curl
          - wget
          - gnupg
          - lsb-release
        state: present

    - name: Install nvm (Node Version Manager)
      shell: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.4/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      environment:
        HOME: "{{ ansible_env.HOME }}"
      args:
        chdir: "{{ ansible_env.HOME }}"
        executable: /bin/bash

    - name: Install Node.js and npm using nvm
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 18
        nvm use 18
      environment:
        HOME: "{{ ansible_env.HOME }}"
      args:
        chdir: "{{ ansible_env.HOME }}"
        executable: /bin/bash

    - name: Clone the devops branch of the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        force: yes

    - name: Install Node.js dependencies
      shell: |
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        npm install
      environment:
        HOME: "{{ ansible_env.HOME }}"
      args:
        chdir: "{{ app_dir }}"
        executable: /bin/bash

    - name: Add hng user with sudo privileges
      user:
        name: hng
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Ensure /var/secrets directory exists
      file:
        path: /var/secrets
        state: directory
        mode: '0755'

    - name: Save PostgreSQL admin credentials
      copy:
        dest: /var/secrets/pg_pw.txt
        content: "{{ db_user }}:{{ pg_password }}"
        mode: '0600'

    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Configure PostgreSQL database
      postgresql_db:
        name: "{{ db_name }}"
        state: present

    - name: Create PostgreSQL user
      postgresql_user:
        name: "{{ db_user }}"
        password: "{{ pg_password }}"
        priv: "ALL"
        state: present

    - name: Ensure RabbitMQ is running
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Configure RabbitMQ
      rabbitmq_user:
        user: guest
        password: guest
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present

    - name: Configure environment variables
      copy:
        dest: "{{ app_dir }}/.env"
        content: |
          DATABASE_URL=postgres://{{ db_user }}:{{ pg_password }}@{{ db_host }}:{{ db_port }}/{{ db_name }}
          RABBITMQ_URL=amqp://guest:guest@localhost:5672/
          PORT=3000
        mode: '0644'

    - name: Start the application
      command: "nohup npm run start:prod > /var/log/stage_5b/out.log 2> /var/log/stage_5b/error.log &"
      args:
        chdir: "{{ app_dir }}"

    - name: Set ownership of log files
      file:
        path: "/var/log/stage_5b"
        state: directory
        recurse: yes
        owner: hng
        group: hng

    - name: Configure Nginx to reverse proxy
      copy:
        dest: /etc/nginx/sites-available/stage_5b
        content: |
          server {
              listen 80;

              server_name _;

              location / {
                  proxy_pass http://127.0.0.1:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }
      notify: Restart nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/stage_5b
        dest: /etc/nginx/sites-enabled/stage_5b
        state: link

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
